const PAGING_SIZE = 5;
const BASE_API_URL = "http://localhost:3000/api/v1";

const LOGIN_CHECKED_REMEMBER_ME = "REMEMBER_ME";

/**
* LOGIN
*/
const LOGIN_USER_INFO_ID = "ID";
const LOGIN_USER_INFO_USERNAME = "USERNAME";
const LOGIN_USER_INFO_FULLNAME = "FULLNAME";